module.exports = {
    extends: [
        'eslint:recommended',
    ],
    rules: {
        'array-callback-return': 'error',
        'arrow-spacing': 'error',
        'block-spacing': 'error',
        'comma-dangle': ['error', 'always-multiline'],
        'curly': 'error',
        'eol-last': ['error', 'always'],
        'eqeqeq': 'error',
        'indent': ['error', 4, { SwitchCase: 1 }],
        'key-spacing': 'error',
        'max-lines': ['warn', { 'max': 400 }],
        'no-trailing-spaces': ['error', { ignoreComments: true }],
        'no-unneeded-ternary': 'warn',
        'no-useless-return': 'error',
        'object-curly-spacing': ['error', 'always'],
        'prefer-const': 'error',
        'prefer-destructuring': ['error', { object: true, array: false }],
        'prefer-promise-reject-errors': 'error',
        'quotes': ['error', 'single'],
        'space-before-function-paren': ['error', {
            anonymous: 'always',
            named: 'never',
            asyncArrow: 'always',
        }],
    },
}
